name: Daily Commit

on:
  schedule:
    - cron: '1 20 * * *'
  workflow_dispatch:

permissions:
  contents: write   # 👈 IMPORTANT

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make change
        run: |
          echo "Update $(date)" >> log.txt

      - name: Commit & Push
        run: |
          git config --global user.name "Azam8808"
          git config --global user.email "azamkhan32451@gmail.com"

          git add .
          git commit -m "Daily auto commit" || echo "No changes"
          git push